### ISSUE TITLE
Проблема с миграцией

### ISSUE THREAD

**Issue by Denkneb** [1vank1n/django-tilda#1]
Здравствуйте!
Не забыта ли миграция после 0001_initial.py
Django предлагает сделать makemigrations
и создается миграция в site-packages/tilda/migrations

**Comment by 1vank1n** [comment]
@Denkneb, день добрый!
Проверил. Миграция не требовалась. Собственно и в коде она присутствует — https://github.com/1vank1n/django-tilda/tree/master/tilda/migrations

Какая версия Django? Последнюю ли версию django-tilda используете? Ну и собственно пришлите файл миграции который создаётся, посмотрим что в нём.

**Comment by Denkneb** [comment]
django-tilda==1.0.6
Django==2.0

`# Generated by Django 2.0.5 on 2018-09-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tildapage',
            options={'ordering': ('title',), 'verbose_name': 'страница', 'verbose_name_plural': 'Tilda Страницы'},
        ),
        migrations.AlterField(
            model_name='tildapage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='tildapage',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='ID страницы'),
        ),
        migrations.AlterField(
            model_name='tildapage',
            name='images',
            field=models.TextField(blank=True, verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='tildapage',
            name='synchronized',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время синхронизиации'),
        ),
        migrations.AlterField(
            model_name='tildapage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
`

**Comment by Denkneb** [comment]
http://prntscr.com/kvp7mf

**Comment by 1vank1n** [comment]
@Denkneb проблема была в том, что для локализации использовал не lazy метод. Поэтому при выставлении русской локали, создавалась миграция на создание verbose_name на русском.

Спасибо, что нашли этот баг. Апдейт сделал. Просто переустановите версию через pip. В новой версии 1.0.7 данной проблемы нет.
