### ISSUE TITLE
Джанго-Тильда

### ISSUE THREAD

**Issue by ansarkg** [1vank1n/django-tilda#14]
Добрый день, установил Ваш модуль для существующего проекта на джанге, так как мне нужно получить материалы созданные на Тильде и опубликовать их от себя, как на вордпрессе, установил, получил список материалов, чтото дальше не пойму как теперь опубликовать полученные материалы с тильды на своем сайте, и еще в админке получил список название темы, а остальные поля пустые почему то. или так и предполагается получить только список?
был бы очень признателен Вам за подсказку

**Comment by ansarkg** [comment]
я хотел его в свой проект добавить, и созданные материалы публиковать с сайта, все сделал по инструкции, и в админке джанги получил список статьей которые сделаны на Тильде. дальше не знаю как продолжить чтобы публиковать материалы с тильды нету инструкции.

**Comment by 1vank1n** [comment]
Если в админке интеграция сработала, то осталось только отрендерить шаблон. В самом конце README есть пример. Продублирую:

```html
<head>
    ...
    {% for css in object.tilda_content.get_css_list %}
        <link rel="stylesheet" href="{{ css }}">
    {% endfor %}
    ...
</head>

<body>
    ...
    {{ object.tilda_content.html|safe }}
    ...
    {% for js in object.tilda_content.get_js_list %}
        <script src="{{ js }}"></script>
    {% endfor %}
</body>
```
