### ISSUE TITLE
Fix url admin

### ISSUE THREAD

**Issue by Denkneb** [1vank1n/django-tilda#2]
Здравствуйте!

Предлагаю исправления для виджета django-tilda/tilda/templates/tilda/widget.html

https://github.com/Denkneb/django-tilda/blob/3f08926477a17e8803013604940e1e8f4bd267e4/tilda/templates/tilda/widget.html#L47
https://github.com/Denkneb/django-tilda/blob/3f08926477a17e8803013604940e1e8f4bd267e4/tilda/templates/tilda/widget.html#L70

Чтобы сделать pull requests не хватает прав)

У нас урл до админ панели немного изменен по желанию заказчика, эти изменения бы решили нашу проблему.

**Comment by Denkneb** [comment]
Было бы круто если бы дали права на Pull request)
если примите изменения

**Comment by 1vank1n** [comment]
@Denkneb никаких ограничений на создание PR нету. Предлагайте PR — я его приму.

**Comment by 1vank1n** [comment]
Собственно создал PR с Вашего репозитория и смёрджил.

**Comment by Denkneb** [comment]
Странно, я не смог создать PR
спасибо)
